micronaut:
  application:
    name: demoR2dbc

r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: H2
      url: r2dbc:h2:mem:///testdb;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ''
      options:
        DB_CLOSE_DELAY: -1
        protocol: mem
